[project]
name = 'vort'
description = ''
authors = []
telemetry = true
cache_dir = '.cache'


[contracts.sip-010-trait]
path = 'contracts/traits/sip-010-trait.clar'
clarity_version = 1
epoch = '2.05'

[contracts.sbtc-token]
path = 'contracts/sbtc-token.clar'
clarity_version = 1
epoch = '2.05'

[contracts.pt-token]
path = 'contracts/pt-token.clar'
clarity_version = 1
epoch = '2.05'

[contracts.yt-token]
path = 'contracts/yt-token.clar'
clarity_version = 1
epoch = '2.05'

[contracts.mock-zest-vault]
path = 'contracts/mock-zest-vault.clar'
clarity_version = 1
epoch = '2.05'

[contracts.tokenizer]
path = 'contracts/tokenizer.clar'
clarity_version = 1
epoch = '2.05'

[contracts.tokenizer-v2]
path = 'contracts/tokenizer-v2.clar'
clarity_version = 1
epoch = '2.05'

[contracts.pt-amm]
path = 'contracts/pt-amm.clar'
clarity_version = 1
epoch = '2.05'

[contracts.pt-amm-v2]
path = 'contracts/pt-amm-v2.clar'
clarity_version = 1
epoch = '2.05'

[contracts.yield-router-v2]
path = 'contracts/yield-router.clar'
clarity_version = 1
epoch = '2.05'

[contracts.tokenizer-v3]
path = 'contracts/tokenizer-v3.clar'
clarity_version = 1
epoch = '2.05'

[contracts.pt-amm-v3]
path = 'contracts/pt-amm-v3.clar'
clarity_version = 1
epoch = '2.05'

[contracts.yield-router-v3]
path = 'contracts/yield-router-v3.clar'
clarity_version = 1
epoch = '2.05'

[contracts.mock-zest-vault-v2]
path = 'contracts/mock-zest-vault-v2.clar'
clarity_version = 1
epoch = '2.05'

[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
